import argparse

parser = argparse.ArgumentParser(description='train')
parser.add_argument('--lenght', type=int, default=15, help='Sentinel-1 img sequence lenght.')
parser.add_argument('--feature', type=int, default=2, help='Sentinel-1 img feature.')
parser.add_argument('--batch', type=int, default=200, help='Number of batch_size to train.')
parser.add_argument('--epoch', type=int, default=40, help='Number of epochs to train.')
parser.add_argument('--val', type=int, default=50, help='size of validation.')
parser.add_argument('--depth', type=int, default=2, help="depth of model")
parser.add_argument('--dropout', type=int, default=0, help="dropout layer")
parser.add_argument('--hidden_dim', type=int, default=150, help='dim of hidden.')
parser.add_argument('--out_lenght', type=int, default=15, help='lenght of output shape.')
parser.add_argument('--corn', type=int, default=2, help='corn.')
parser.add_argument('--img_path', type=str, default='img.tif', help='img path.')
parser.add_argument('--cloud_img_path', type=str, default='Cloud cover.tif', help='cloud cover img.')
parser.add_argument('--S1_tr_path', type=str, default='S1_tr.pickle', help='S1 train path.')
parser.add_argument('--S2_tr_path', type=str, default='S2_tr.pickle', help='S2 train path.')
parser.add_argument('--S1_te_path', type=str, default='S1_te.pickle', help='S1 test path.')
parser.add_argument('--S2_te_path', type=str, default='S2_te.pickle', help='S2 test path.')
parser.add_argument('--te_label_path', type=str, default='te_label.pickle', help='crop type data path.')
parser.add_argument('--optimizer', type=str, default='rmsprop', help='optimizer.')
parser.add_argument('--pred_name', type=str, default='pred_S2.tif', help='pred img (Sentinel-2 NDVI time series)')
parser.add_argument('--name', type=str, default='SimpleRNN', help='model name.')
parser.add_argument("--run_mode", action="store_true",default="train")
parser.add_argument('--color', type=str, default='CMRmap_r', help='color.')
parser.add_argument('--jpgname', type=str, default='diff', help='contrast.')
args =parser.parse_args()

